HorasExtra/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;
using HorasExtra.Data;
using HorasExtra.Models;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using Microsoft.AspNetCore.Mvc;
namespace HorasExtra.Controllers
{
    public class EmployeesController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly HorasExtraDBContext _context;
        private Sp Sp = new Sp();
        public EmployeesController(HorasExtraDBContext context)
        {
            _context = context;
        }
        [System.Web.Mvc.HttpPost]
        public Microsoft.AspNetCore.Mvc.JsonResult GetEmployeeData(int EmpNum)
        {
            return Json(Sp.GetEmpData(EmpNum));
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // GET: Employees/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        public async Task<IActionResult> Create([Microsoft.AspNetCore.Mvc.Bind("ID,EmpNum,Name,HrsToWork,Signature,CreatedAt,RequestID")] Employees employees)
        {
            if (ModelState.IsValid)
            {
                employees.CreatedAt = DateTime.Now;
                _context.Add(employees);
                await _context.SaveChangesAsync();
            }
            return View("Requests/Details/" + employees.RequestID.ToString());
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees.FindAsync(id);
            if (employees == null)
            {
                return NotFound();
            }
            return View(employees);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Microsoft.AspNetCore.Mvc.HttpPost]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Microsoft.AspNetCore.Mvc.Bind("ID,EmpNum,Name,QtyHrs,Signature,CreatedAt,ID_Request")] Employees employees)
        {
            if (id != employees.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employees);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    if (!EmployeesExists(employees.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.ID == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // POST: Employees/Delete/5
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.ActionName("Delete")]
        [Microsoft.AspNetCore.Mvc.ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employees = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employees);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeesExists(int id)
        {
            return _context.Employees.Any(e => e.ID == id);
        }
    }
}

HorasExtra/Controllers/RequestsController.cs
using System;
using HorasExtra.Data;
using HorasExtra.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Linq;

namespace HorasExtra.Controllers
{
    public class RequestsController : Controller
    {
        private readonly HorasExtraDBContext _context;
        Sp sp = new Sp();
        public RequestsController(HorasExtraDBContext context)
        {
            _context = context;
        }
        // GET: RequestsControllercs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Request.ToListAsync());
        }


        // GET: RequestsControllercs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FirstOrDefaultAsync(m => m.ID_request == id);

            var blogs = _context.Employees.FromSqlRaw($"EXECUTE dbo.GetEmployeeByIDReq {id.ToString()}").ToList();

            request.Employees = blogs;
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: RequestsControllercs/Create
        public ActionResult Create()
        {
            return View();

        }

        // POST: RequestsControllercs/Create
        [HttpPost]
        public JsonResult Create([Bind("ID_request,Operation,Department,CreatedDate,WorkSchedule,ManagerSignature,SupervisorSignature")] Request request)
        {
            request.CreatedDate = DateTime.Now;
            request.UpdatedAt = DateTime.Now;
            return Json(sp.SaveRequest(request));
        }

        // GET: RequestsControllercs/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RequestsControllercs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RequestsControllercs/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RequestsControllercs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HorasExtra/Views/Requests/Create.cshtml
@model HorasExtra.Models.Request

@{
    ViewData["Title"] = "Create";
}




<div class="container-fluid">
    <div class="row">
        <h1>Crear Solicitud de tiempo extra</h1>
    </div>
    <div class="row">
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <div class="row row-cols-12">
                    <div class="col">

                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label asp-for="ManagerSignature" class="control-label"></label>
                            <div id="signature-pad" class="signature-pad">
                                <div class="signature-pad--body">
                                    <canvas id="ImgManagerSignature"></canvas>
                                </div>
                                <div class="signature-pad--footer">
                                    <div class="signature-pad--actions">
                                        <div>
                                            <button type="button" class="button clear" data-action="clear">Clear</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="ManagerSignature" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SupervisorSignature" class="control-label"></label>
                            <div id="signature-pad2" class="signature-pad">
                                <div class="signature-pad--body">
                                    <canvas id="ImgSupervisorSignature"></canvas>
                                </div>
                                <div class="signature-pad--footer">
                                    <div class="signature-pad--actions">
                                        <div>
                                            <button type="button" class="button clear" data-action="clear">Clear</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>

    $(document).ready(function () {

        $("#submitButton").click(function (e) {

            var canvas1 = document.getElementById('ImgSupervisorSignature');
            var SupervisorSignatureBase64 = canvas1.toDataURL('image/png')

            var canvas2 = document.getElementById('ImgManagerSignature');
            var ManagerSignatureBase64 = canvas2.toDataURL('image/png')
h

            var data = {
                Operation: $("#DDOperation").val(),
                Department: $("#txtDepartment").val(),
                WorkSchedule: $("#txtSchedule").val(),
                ManagerSignature: ManagerSignatureBase64,
                SupervisorSignature: SupervisorSignatureBase64
            }

            console.log(data);

            $.post('@Url.Action("Create", "Requests")', { request: data, }, function (AddR) {
                
            });

            //$.ajax({
            //    type: "POST",
            //    url: "Requests/Create",
            //    contentType: "application/json; charset=utf-8",
            //    dataType: "json",
            //    data: JSON.stringify({
            //        Operation: $("#DDOperation").val(),
            //        Department: $("#txtDepartement").val(),
            //        WorkSchedule: $("#txtSchedule").val(),
            //        ManagerSignature: ManagerSignatureBase64,
            //        SupervisorSignature: SupervisorSignatureBase64,
            //    }),
            //    success: function (result, status, xhr) {
            //        alert('Guardado');
            //    },
            //    error: function (jqXHR, exception) {
            //        var msg = '';
            //        if (jqXHR.status === 0) {
            //            msg = 'Not connect.\n Verify Network.';
            //        } else if (jqXHR.status == 404) {
            //            msg = 'Requested page not found. [404]';
            //        } else if (jqXHR.status == 500) {
            //            msg = 'Internal Server Error [500].';
            //        } else if (exception === 'parsererror') {
            //            msg = 'Requested JSON parse failed.';
            //        } else if (exception === 'timeout') {
            //            msg = 'Time out error.';
            //        } else if (exception === 'abort') {
            //            msg = 'Ajax request aborted.';
            //        } else {
            //            msg = 'Uncaught Error.\n' + jqXHR.responseText;
            //        }
            //        console.log(msg);
            //    }
            //});
        });

        var divfirma1 = "signature-pad";
        var divfirma2 = "signature-pad2";

        var wrapper1 = document.getElementById(divfirma1);
        var clearButton = wrapper1.querySelector("[data-action=clear]")
        var canvas = wrapper1.querySelector("canvas");
        var signaturePad = new SignaturePad(canvas, {
            backgroundColor: 'rgb(255, 255, 255)'
        });

        clearButton.addEventListener("click", function (event) {
            signaturePad.clear();
        });


        var wrapper2 = document.getElementById(divfirma2);
        var clearButton2 = wrapper2.querySelector("[data-action=clear]")
        var canvas = wrapper2.querySelector("canvas");
        var signaturePad2 = new SignaturePad(canvas, {
            backgroundColor: 'rgb(255, 255, 255)'
        });

        clearButton2.addEventListener("click", function (event) {
            signaturePad2.clear();
        });


        //function resizeCanvas() {
        //    var ratio = Math.max(window.devicePixelRatio || 1, 1);
        //    canvas.width = canvas.offsetWidth * ratio;
        //    canvas.height = canvas.offsetHeight * ratio;
        //    canvas.getContext("2d").scale(ratio, ratio);
        //    signaturePad.clear();
        //    signaturePad2.clear();
        //}

        //window.onresize = resizeCanvas;
        //resizeCanvas();



        //function Validate() {
        //    var errorCounter = 0;
        //    $(".nameSpan").text("");
        //    $(".ageSpan").text("");
        //    $(".standardSpan").text("");
        //    $(".percentSpan").text("");
        //    $(".statusSpan").text("");

        //    if ($("#name").val() == "") {
        //        $(".nameSpan").text("Please enter name");
        //        errorCounter++;
        //    }

        //    if ($("#age").val() == "") {
        //        $(".ageSpan").text("Please enter age");
        //        errorCounter++;
        //    }
        //    else if (!(isPositiveInteger($("#age").val()))) {
        //        $(".ageSpan").text("Age should be in +ve integers");
        //        errorCounter++;
        //    }

        //    if ($("#standard").val() == "") {
        //        $(".standardSpan").text("Please enter standard");
        //        errorCounter++;
        //    }

        //    if ($("#percent").val() == "") {
        //        $(".percentSpan").text("Please enter percent");
        //        errorCounter++;
        //    }
        //    else if (!(isPercent($("#percent").val()))) {
        //        $(".percentSpan").text("Percent should be integers or decimal");
        //        errorCounter++;
        //    }

        //    if ($("#status").val() == "Select") {
        //        $(".statusSpan").text("Please select status");
        //        errorCounter++;
        //    }

        //    if (errorCounter == 0) {
        //        return true;
        //    }
        //    else {
        //        return false;
        //    }
        //}

        //function isPositiveInteger(n) {
        //    return ($.isNumeric(n) && (n > 0));
        //}

        //function isPercent(n) {
        //    return (n.match(/(^100(\.0{1,2})?$)|(^([1-9]([0-9])?|0)(\.[0-9]{1,2})?$)/));
        //}
    });
</script>

HorasExtra/Views/Requests/Delete.cshtml
@model HorasExtra.Models.Request

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Request</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Operation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Operation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkSchedule)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkSchedule)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManagerSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManagerSignature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupervisorSignature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupervisorSignature)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID_request" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HorasExtra/Views/Requests/Details.cshtml
@model HorasExtra.Models.Request

@{
    ViewData["Title"] = "Details";
}

<style>
    canvas {
        display: block;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <h1>Agregar empleados</h1>
    </div>
    <div class="row">
        <div class="card" style="width: 100%;">
            <div class="card-body">
                <div class="row row-cols-12">
                    <div class="col">
                        <div class="form-group">
                            <label for="ID_Request">Numero de solicitud</label>
                            <input id="LblId" type="text" class="form-control input-full" value="@Html.DisplayFor(model => model.ID_request)" />
                        </div>
                        <div class="form-group">
                            <label for="ID_Request">Operacion</label>
                            <input id="ID_operation" type="text" class="form-control input-full" value="@Html.DisplayFor(model => model.Operation)" />
                        </div>
                        <div class="form-group">
                            <label for="ID_Request">Departamento</label>
                            <input id="ID_Request" type="text" class="form-control input-full" value="@Html.DisplayFor(model => model.Department)" />
                        </div>
                        <div class="form-group">
                            <label for="ID_Request">Fecha</label>
                            <input id="ID_Request" type="text" class="form-control input-full" value="@Html.DisplayFor(model => model.CreatedDate)" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <h5 class="card-title">Firma de gerente</h5>
                            <img width="300" height="100" src="@Html.DisplayFor(model => model.ManagerSignature)" class="card-img-bottom" alt="...">
                        </div>
                        <div class="form-group">
                            <h5 class="card-title">Firma de Supervisor</h5>
                            <img width="300" height="100" src="@Html.DisplayFor(model => model.ManagerSignature)" class="card-img-bottom" alt="...">
                        </div>
                    </div>
                    <div class="col">
                        <div>
                            <label>Codigo QR</label>
                            <div id="qrcode"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <input id="BtnOpenEmpModal" type="submit" class="btn btn-secondary" value="Agregar Empleado" />
    </div>

    <div class="row">
        <div class="table table-responsive">
            <table class="table-striped" id="TableEmp">
                <thead>
                    <tr>
                        <th scope="col">
                            Numero de empleado
                        </th>
                        <th scope="col">
                            Nombre de empleado
                        </th>
                        <th scope="col">
                            Cantidad de horas
                        </th>
                        <th scope="col">
                            Firma
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Employees)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.EmpNum)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.HrsToWork)
                            </td>
                            <td>
                                <img width="250" height="75" src="@Html.DisplayFor(modelItem => item.Signature)" />
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>





<div class="modal fade" id="ModalAddEmployee" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #2a2f5b;">
                <h5 class="modal-title" id="staticBackdropLabel" style="color:whitesmoke;">Registrar empleado</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span style="color:whitesmoke;" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label">Employee Number</label>
                    <input id="EmpNum" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">Name</label>
                    <input id="txtName" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">Hours Quantity</label>
                    <input id="txtHrsQty" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="control-label">Signature</label>
                    <div id="signature-pad" class="signature-pad">
                        <div class="signature-pad--body shadow-lg p-3 mb-5 bg-white rounded">
                            <canvas id="ImgEmployeeSignature" style="width: 100%;" class="rounded"></canvas>
                        </div>
                    </div>
                    <div class="signature-pad--footer">
                        <div class="signature-pad--actions">
                            <div>
                                <button id="BtnClearSignature" type="button" class="button clear" data-action="clear">Clear</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer" style="background-color: #2a2f5b;">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="BtnSaveEmployee" class="btn btn-success">Guardar</button>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID_request">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</div>
<script>

    $(document).ready(function () {

        $("#EmpNum").on("focusout", function () {

            $.get('@Url.Action("GetEmployeeData", "Employees")', { EmpNum: $("#EmpNum").val(), }, function (AddR) {
                var result = JSON.parse(AddR);

                $("#txtName").val(result[0].Name);
            });

        });


        $("#BtnOpenEmpModal").click(function () {

            $("#ModalAddEmployee").modal({ backdrop: 'static', keyboard: false }, "show");
        });
        SignatureDesing();
        $("#BtnSaveEmployee").click(function (e) {

            var canvas1 = document.getElementById('ImgEmployeeSignature');
            var SignatureBase64 = canvas1.toDataURL('image/png');

            var data = {
                EmpNum: $("#EmpNum").val(),
                Name: $("#txtName").val(),
                QtyHrs: $("#txtHrsQty").val(),
                Signature: SignatureBase64,
                RequestID: $("#LblId").val()
            };

            $.post('@Url.Action("Create", "Employees")', { employees: data, }, function (AddR) {
                alert("Guardado");
            });

        });


        //Guardar Firma
        var divfirma1 = "signature-pad";
        var wrapper1 = document.getElementById(divfirma1);
        var canvas = wrapper1.querySelector("canvas");
        var signaturePad = new SignaturePad(canvas, {
            backgroundColor: 'rgb(255, 255, 255)'
        });

        $("#BtnClearSignature").click(function () {
            signaturePad.clear();
        });
        //Guardar Firma

        //Crear QR
        var table = document.getElementById("TableEmp");
        var tbodyRowCount = table.tBodies[0].rows.length;
        const qrcode = new QRCode(document.getElementById('qrcode'), {
            text: (
                "IDREQ:" + $("#LblId").val() +
                "Operation:" + $("#Operation").text().trim() +
                "CreatedAt:" + $("#Date").text().trim() +
                "EmpQty:" + tbodyRowCount),
            width: 128,
            height: 128,
            colorDark: '#000',
            colorLight: '#fff',
            correctLevel: QRCode.CorrectLevel.H
        });
        //Crear QR

        function SignatureDesing() {
            const canvas = document.getElementById('ImgEmployeeSignature');
            const context = canvas.getContext('2d');
            window.addEventListener('resize', resizeCanvas, false);
            function resizeCanvas() {
                //canvas.width = window.innerWidth;
                //canvas.height = window.innerHeight;
                canvas.width = 740;
                canvas.height = 150;

                drawStuff();
            }

            resizeCanvas();

            function drawStuff() {
            }
        }
    });

</script>

HorasExtra/Views/Requests/Edit.cshtml
@model HorasExtra.Models.Request

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Request</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID_request" />
            <div class="form-group">
                <label asp-for="Operation" class="control-label"></label>
                <input asp-for="Operation" class="form-control" />
                <span asp-validation-for="Operation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkSchedule" class="control-label"></label>
                <input asp-for="WorkSchedule" class="form-control" />
                <span asp-validation-for="WorkSchedule" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerSignature" class="control-label"></label>
                <input asp-for="ManagerSignature" class="form-control" />
                <span asp-validation-for="ManagerSignature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupervisorSignature" class="control-label"></label>
                <input asp-for="SupervisorSignature" class="form-control" />
                <span asp-validation-for="SupervisorSignature" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}